### ISSUE TITLE
Import ERROR

### ISSUE THREAD

**Issue by jg0014** [grimoire/torch2trt_dynamic#38]
tensorrt                  8.4.1.5

>>> import torch2trt_dynamic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home_orin/anaconda3/envs/track2/lib/python3.8/site-packages/torch2trt_dynamic/__init__.py", line 3, in <module>
    from .converters import *  # noqa: F401,F403
  File "/home_orin/anaconda3/envs/track2/lib/python3.8/site-packages/torch2trt_dynamic/converters/__init__.py", line 19, in <module>
    from . import grid_sample  # noqa: F401
  File "/home_orin/anaconda3/envs/track2/lib/python3.8/site-packages/torch2trt_dynamic/converters/grid_sample.py", line 8, in <module>
    bicubic=trt.ResizeMode.CUBIC)
AttributeError: type object 'tensorrt.tensorrt.ResizeMode' has no attribute 'CUBIC'

**Comment by grimoire** [comment]
Update tensorrt version or just remove bicubic resize model in `torch2trt_dynamic/converters/grid_sample.py`.
