### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zkloveai** [grimoire/torch2trt_dynamic#5]
(zk_mmdet2.4) yyf@zyzn:~/software/torch2trt$ sudo python setup.py install
[sudo] password for yyf: 
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from build import build
  File "/home/yyf/software/torch2trt/build.py", line 29, in <module>
    torch_dir=imp.find_module('torch')[1],
ImportError: No module named torch
 
I install pytorch already.why ?

**Comment by zhiqwang** [comment]
I guess `sudo` here maybe cause this problem?

**Comment by hxyucas** [comment]
you should change the build.py in line 28 as torch_dir= 'XX/python3.8/site-packages/torch',,it really works
